# Generated by Django 4.0.3 on 2022-08-24 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_score_result_exam_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
    ]
