# Generated by Django 4.0.3 on 2022-08-24 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_course_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='level',
        ),
        migrations.RemoveField(
            model_name='student',
            name='program',
        ),
    ]
